### PR TITLE
Fixing compiliation on Ubuntu

### PR DESCRIPTION
**Pull request by saeschdivara**
Hi

I have just tried to compile on my Ubuntu machine but I got a compiling error in the pushover frontend.
I fixed it since it was just a small thing.

### CODE REVIEW

**Comment by TheOneRing** [comment]
Hi thanks for the patch. What is the error message and what's your setup (compiler & qt version)?
I just want to find out why you got that error.

**Comment by saeschdivara** [comment]
I have Ubuntu 14.04, compiler is g++ and Qt version is 5.4.2

**Comment by TheOneRing** [comment]
And the build error :smile:

**Comment by saeschdivara** [comment]
/Snorenotify/src/plugins/frontends/pushover_frontend/pushover_frontend.cpp:163:6: error: no matching function for call to 'PushoverFrontend::connect(QPointer<QWebSocket>&, void (QWebSocket::*)(const QByteArray&), PushoverFrontend::connectToService()::__lambda4)'
     });
      ^
Qt/5.4/gcc_64/include/QtCore/qobject.h:196:36: note: static QMetaObject::Connection QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static QMetaObject::Connection connect(const QObject *sender, const char *signal,

Qt/5.4/gcc_64/include/QtCore/qobject.h:199:36: note: static QMetaObject::Connection QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static QMetaObject::Connection connect(const QObject *sender, const QMetaMethod &signal,

Snorenotify/src/plugins/frontends/pushover_frontend/pushover_frontend.cpp:177:6: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QWebSocket>'
     });
      ^

And so forth.
Do you need more?

**Comment by TheOneRing** [comment]
Thanks, I know it is exhausting but could you please post the complete error message :)
This should actually compile and it did on most systems. 
And which version of gcc?

**Comment by saeschdivara** [comment]
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

**Comment by TheOneRing** [comment]
Cherry-picked it to the kde repo. Thanks. It is a problem related to gcc 4.8.

**Pull request closed without merging**
